title: UXIndonesia (UXID)
email: hello@uxindonesia.org
description: >
  An open community of user experience designers in Indonesia.
baseurl: ""
url: "http://localhost:4000"
twitter_username: uxindonesia
github_username:  uxindonesia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
